config/routes.rb
Rails.application.routes.draw do
  get 'document/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  # get 'user/show/' => 'user#show' ,as: :mypage
  # get '/user/show/:id', to: 'user#show', as: 'patient'
 
  # get 'subject/index'
  # get 'subject/show'
  # get 'home/index'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :user, only: [:show] 
  # get  '/user/:id' ,to: 'user#show',as: 'user'
  
  # Defines the root path route ("/")
  # root "articles#index"
  resources:subject
  
  resources:document, except: [:index_api,:destroy_api]

  get 'document/api/index' => 'document#index_api'
  delete 'document/delete/:id' => 'document#destroy_api'

  
  
  post "document/new" => "document#create"



  root to: "subject#index"
end

app/models/subject.rb
class Subject < ApplicationRecord
    validates :subjectname, presence: true
    
end

app/controllers/subject_controller.rb
class SubjectController < ApplicationController
  before_action :authenticate_user!

  def index
    @parameter = params[:group]
    @parameter = 'all' if @parameter == ''

    @page_param = params[:pagenation]
    @subject = if @parameter == 'is'
                 Subject.where(username: current_user.name).and(Subject.where(test: 0))
               elsif @parameter == 'notis'
                 Subject.where(username: current_user.name).and(Subject.where(test: 1))
               elsif @parameter == 'all'
                 Subject.where(username: current_user.name)
               else
                 Subject.where(username: current_user.name)
               end
    @pagenumber = (@subject.count / 12).to_i
    @pagenation = @page_param.to_i

    if @subject.count < (@pagenation - 1) * 12
      @pagenation -= 1

    elsif @pagenation <= 0
      @pagenation = 1
    end
  end

  def new
    @subject = Subject.new
  end

  def create
    @subject = Subject.create(subject_params)
    if @subject.save!
      redirect_to document_new_path(content: @subject.subjectname), notice: '作成しました.'
    else
      render :new
    end
  end

  def edit
    @subject = Subject.find(params[:id])
  end

  def update
    subject = Subject.find(params[:id])
    if subject.update(subject_params)
      redirect_to root_path, notice: '更新しました'
    else
      render action: :edit, notice: '変更に誤りがあります。'
    end
  end

  def destroy
    subject = Subject.find(params[:id])
    Document.where(username: subject.username).and(Document.where(subjectname: subject.subjectname)).destroy_all
    subject.destroy
    redirect_to root_path
  end

  private

  def subject_params
    params.require(:subject).permit(:username, :subjectname, :test)
  end
end

app/helpers/subject_helper.rb
module SubjectHelper
end

app/views/subject/edit.html.erb
<section class="hero is-success">
<div class="hero-body">
  <p class="title">
    教科作成
  </p>
  <p class="subtitle">
    作成する教科の名前とテストの有無を入力してください。
  </p>
</div>
</section>

<section class="container" style="margin-top:5%;">
  <div class="colums is-centered">
      <%= form_for @subject,url:subject_path do |f|%>
          <%= f.hidden_field :username,:value => current_user.name %>
            <div class = "field">
                <%=f.label:教科名,class:"label"%>
                <p class="control has-icons-left">
                    <%=f.text_field:subjectname,class:"input"%>
                    <span class="icon is-small is-left">
                        <ion-icon name="book-outline"></ion-icon>
                    </span>
                </p>
            </div>
            <div class = "field" style="margin-top:3%;">
                <%=f.label:test,class:"label"%>
                    <%=f.select:test, [['あり',0],['なし',1]], { include_blank: false, selected: 0 } %>
            </div>
            <div class="buttons" style="margin-top:3%;">
                <%= f.submit "更新", class:"button is-info"%>
            </div>
      <%end%>
  </div>
</section>

app/views/subject/index.html.erb
<section class="hero is-success">
    <div class="hero-body">
        <h1 class="title">教科一覧</h1>
    </div>
</section>

<section>
    <div class="container" style="margin-top:5%;">
        <article class="panel is-primary">
            <div class="tabs">
                <ul>
                    <li id="all"><%=link_to "All",subject_index_path(pagenation:1, group:"all")%></li>
                    <li id="is"><%=link_to "あり",subject_index_path(pagenation:1, group:"is")%></li>
                    <li id="notis"><%=link_to "なし",subject_index_path(pagenation:1, group:"notis")%></li>
                </ul>                                                  
            </div>
            <div class="parent">
                <button class="item button" id="item2"><%= link_to '作成' ,new_subject_path %></button>
                <button class="item button" id="edit" onclick="editbutton()">編集</button>
                <button class="item button" id="delete" onclick="deletebutton()"><ion-icon name="trash-outline"></ion-icon></button>
                
            </div>
            <% @subject.slice((@pagenation-1)*12..@pagenation*12).each do |s|%>
                <div class="panel-block">
                
                    <input type="checkbox"  id="id#{s.id}" value= "<%=s.id%>" name="options" onclick="check_search()">
                    <span class="panel-icon">
                        <ion-icon name="folder-open-outline"></ion-icon>
                    </span>
                    <%= link_to s.subjectname,:controller => 'document', :action => 'index', content: s.subjectname,pagenation:1%>
                    <div style="display:none;">
                        <%= button_to "削除",subject_path(id:s.id),{method: :delete,id:s.id,form:{data: {turbo_confirm:"削除しますか?"}}}%>
                        <%= button_to "編集","/subject/#{s.id}/edit",{method: :get,name:s.id}%>
                    </div>
                </div>
            <%end%>
        </article>
    </div>
    <footer class="footer">
        <div class="content has-text-centered">
            <nav class="pagination is-centered" role="navigation" aria-label="pagination">
                <a class="pagination-previous"  href="./subject?group=<%=@parameter%>&pagenation=<%=@pagenation-1%>">Previous</a>
                <a class="pagination-next" href="./subject?group=<%=@parameter%>&pagenation=<%=@pagenation+1%>">Next page</a>
                <ul class="pagination-list">
                    <li><a class="pagination-link"  aria-label="Goto page 1" href="./subject?group=<%=@parameter%>&pagenation=<%=@pagenation%>"><%=@pagenation%></a></li>
                    <li><a class="pagination-link"  aria-label="Goto page 1" href="./subject?group=<%=@parameter%>&pagenation=<%=@pagenation+1%>"><%=@pagenation+1%></a></li>                                
                    <li><span class="pagination-ellipsis">&hellip;</span></li>                   
                </ul>
            </nav>
        </div>
    </footer>
</section>

<%= javascript_include_tag "subject.js" %>

app/views/subject/new.html.erb
<section class="hero is-success">
  <div class="hero-body">
    <p class="title">
      教科作成
    </p>
    <p class="subtitle">
      作成する教科の名前とテストの有無を入力してください。
    </p>
  </div>
</section>

<% if @subject.errors.any?%>
<p>error</p>
<%end%>

<section class="container" style="margin-top:5%;">
  <div class="colums is-centered">
    <%= form_for @subject,url:subject_index_path do |f|%>
      <%= f.hidden_field :username,:value => current_user.name %>
      <div class = "field">
          <%=f.label:教科名,class:"label"%>
          <p class="control has-icons-left">
              <%=f.text_field:subjectname,class:"input"%>
              <span class="icon is-small is-left">
                  <ion-icon name="book-outline"></ion-icon>
              </span>
          </p>
      </div>
      <div class = "field" style="margin-top:3%;">
          <%=f.label:test,class:"label"%>
              <%=f.select:test, [['あり',0],['なし',1]], { include_blank: false, selected: 0 } %>
      </div>
      <div class="buttons" style="margin-top:3%;">
          <%= f.submit "作成", class:"button is-info"%>
      </div>
    <%end%>
  </div>
</section>

app/views/subject/show.html.erb
<div class="hero is-primary">
    <div class="section">
        <div class="title">
            <%=@subject.subjectname%>
        </div>
    </div>
</div>

<% if !@subject.test%>
    <h1>テストあり</h1>
<%end%>