config/routes.rb
Rails.application.routes.draw do
  get 'document/index'
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
 
  # get 'user/show/' => 'user#show' ,as: :mypage
  # get '/user/show/:id', to: 'user#show', as: 'patient'
 
  # get 'subject/index'
  # get 'subject/show'
  # get 'home/index'
  devise_for :users

  devise_scope :user do
    get '/users/sign_out' => 'devise/sessions#destroy'
    
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :user, only: [:show] 
  # get  '/user/:id' ,to: 'user#show',as: 'user'
  
  # Defines the root path route ("/")
  # root "articles#index"
  resources:subject
  
  resources:document, except: [:index_api,:destroy_api]

  get 'document/api/index' => 'document#index_api'
  delete 'document/delete/:id' => 'document#destroy_api'

  
  
  post "document/new" => "document#create"



  root to: "subject#index"
end

app/models/document.rb
class Document < ApplicationRecord
    validates :title ,presence:true

   
end

app/controllers/document_controller.rb
class DocumentController < ApplicationController
  before_action :authenticate_user!
  
  def index_api
    user_name = Document.where(username: current_user.name)
    subject_name = Document.where(subjectname: params[:content])
    render json:user_name.and(subject_name)
  end

  def show
    @document = Document.find(params[:id])
  end

  def new
    @document = Document.new
  end

  def create
    modified_params = params_modify(params.require(:document))
    document = Document.create(modified_params)
    if document.save
      redirect_to document_path(document, content: params[:content]), notice: '作成しました.'
    else
      render :new
    end
  end

  def destroy
    document = Document.where(id:params[:id])
    document.destroy_all
    redirect_to document_index_path(content: params[:content], pagenation: params[:pagenation])
  end

  def destroy_api
    document = Document.find(params[:id])
    document.destroy
  end

  def edit
    @document = Document.find(params[:id])
  end

  def update
    modified_params = params_modify(params.require(:document))
    document = Document.find(params[:id])
    if document.update(modified_params)
      redirect_to document_path(document, content: params[:content]), notice: '更新しました。'
    else
      render :edit
    end
  end

  private

  def params_modify(params)
    if params == nil
      p 'params is nil'
      return
    end

    params[:title] = 'no title' if params[:title] == ''
    params[:difficulty] = case params[:difficulty]
                          when '1','2'
                            'easy'
                          when '3'
                            'medium'
                          when '4','5'
                            'difficult'
                          else
                            'all'
                          end
    return params.permit(:username, :subjectname, :title, :content, :difficulty)
  end

end

app/helpers/document_helper.rb
module DocumentHelper
end

app/views/document/edit.html.erb
<section class="hero is-success">
<div class="hero-body">
  <p class="title">
    資料更新
  </p>
  <p class="subtitle">
    資料の情報を編集してください。
  </p>
</div>
</section>
<section class="container">
    <div style="margin-top:5%;">
        <%= form_for @document,url:document_path(content:params[:content]) do |f|%>
            <%= f.hidden_field :username,:value => current_user.name %>
            <%= f.hidden_field :subjectname,:value => params[:content] %>
            <div class="field">
                <%= f.label:"タイトル",class:"label"%>
                <%= f.text_field:title,class:"input",style:"border-width:thin; border-color:#2f4f4f;"%>
            </div>
            <div class="field" style="margin-top:3%">
                <%= f.label:"内容",class:"label"%>
                <%= f.text_area:content,class:"textarea",placeholder:"10 lines of textarea",rows:"10" ,style:"border-width:thin; border-color:#2f4f4f;"%>
            </div>
            <div class="field" style="margin-top:3%">
                <%= f.label:"難易度",class:"label"%>
                <%= f.number_field:difficulty,min:1,max:5%>
            </div>
            <%=f.submit "更新",class:"button is-info",style:"margin-top:1%"%>
        <%end%>
    </div>
</section>

app/views/document/index.html.erb
<section class="hero is-success">
<div class="hero-body">
    <h1 class="title"><%=params[:content]%>資料一覧</h1>
</div>
</section>
<input id="type-nav" value="<%= @nav %>" type="hidden"/>
<section>
    <div id="app">
        <div class="container" style="margin-top:5%;">
            <div class="tabs">
                <ul>
                    <a id="all" @click="ClickNav($event)" style="color:#1e90ff;" >全て</a>
                    <a id="difficult" @click="ClickNav($event)" style="color:#1e90ff;">重要</a>
                    <a id="medium" @click="ClickNav($event)" style="color:#1e90ff;">普通</a>
                    <a id="easy" @click="ClickNav($event)" style="color:#1e90ff;">そんなに</a>
                </ul>
            </div>
            
            <div class="parent">
                <button class="item button"><%= link_to '作成' ,new_document_path(content:params[:content]) %></button>
                <button class="item button" ref="trash" @click="TrashOn()"><ion-icon name="trash-outline"></ion-icon></button>
            </div>

            <article class="panel is-primary" v-if="menu_type == 'all'" style="padding:5px;">
                <div v-for='item in message' class="subject">
                    <label>
                        <input type="checkbox" name="options" v-model="item.checked" ref='checkbox' @click="TrashActive($event,item)" :value='item.title' :id="item.id">
                        <span class="panel-icon">
                            <ion-icon name="bookmark-outline"></ion-icon>
                        </span>
                            <a :href=item.id+'?content='+title>{{ item.title }}</a>
                    </label>
                </div>
            </article>
           
            <article v-else class="panel is-primary">
                <div v-for='item in message'>
                    <div class="panel-block" v-if="menu_type == item.difficulty"  ref="itemlist"> 
                        <label style="margin:10px;">
                            <input type="checkbox" name="options" v-model="item.checked" ref='checkbox' @click="TrashActive($event,item)" :value='item.title' :id="item.id">
                            <span class="panel-icon">
                                <ion-icon name="bookmark-outline"></ion-icon>
                            </span>
                                <a :href=item.id+'?content='+title>{{ item.title }}</a>
                        </label>
                    </div>
                </div>
            </article>
        </div>
    </div>
</section>


<style>
.item{
    margin-left:10px;
    margin-top:auto;
}
.parent{
    display: flex;
    flex-wrap: wrap;
    align-items:center
    width: 600px;
    margin-bottom:10px;
}
.subject{
    margin:20px 10px 20px 10px;
}

</style>
<%= javascript_include_tag "document.js" %>

app/views/document/new.html.erb
<section class="hero is-success">
<div class="hero-body">
  <p class="title">
    資料作成
  </p>
  <p class="subtitle">
    作成する資料の情報を入力してください。
  </p>
</div>
</section>
<section class="container">
    <div style="margin-top:5%;">
        <%= form_for @document,url:document_new_path(content:params[:content]) do |f|%>
            <%= f.hidden_field :username,:value => current_user.name %>
            <%= f.hidden_field :subjectname,:value => params[:content] %>
            <div class="field">
                <%= f.label:"タイトル",class:"label"%>
                <%= f.text_field:title,class:"input",style:"border-width:thin; border-color:#2f4f4f;"%>
            </div>
            <div class="field" style="margin-top:3%">
                <%= f.label:"内容",class:"label"%>
                <%= f.text_area:content,class:"textarea",placeholder:"10 lines of textarea",rows:"10" ,style:"border-width:thin; border-color:#2f4f4f;"%>
            </div>
            <div class="field" style="margin-top:3%">
                <%= f.label:"難易度",class:"label"%>
                <%= f.number_field:difficulty,min:1,max:5%>
            </div>
            <%=f.submit "作成",class:"button is-info",style:"margin-top:1%"%>
        <%end%>
    </div>
</section>

app/views/document/show.html.erb
<section class="hero is-success">
    <div class="hero-body">
        <p class="title">
            資料閲覧
        </p>
    </div>
</section>

<section class="container" style="margin-top:5%;">
    <h1 class="title"><%=@document.title%></h1>
    <p class="subtitle">重要度:<%=@document.difficulty%></p>
    <div class="parent">
        <button class="item button" id="item2"><%= link_to '編集' ,edit_document_path(content:params[:content]) %></button>
        <%= button_to document_path(@document.id,content:params[:content]),class:"item button is-danger", method: :delete ,form:{data: {turbo_confirm:"削除しますか?"}} do%>
            <ion-icon name="trash-outline">
        <%end%>
    </div>
    <div class="card">
        <div class="card-content">
            <div class="content">
                <%=markdown(@document.content)%>
            </div>
        </div>
    </div>
    <%= link_to "資料一覧へ",document_index_path(content:params[:content],pagenation:1)%>
</section>

<style>
.item{
    margin-left:10px;
    margin-top:auto;
}
.parent{
    display: flex;
    flex-wrap: wrap;
    align-items:center
    width: 600px;
}

</style>